services:
  node:
    build: ./backend    
    container_name: node_service
    restart : always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend-network
    environment:
      - NODE_ENV=development
  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file: 
      - .env
networks:
  backend-network:

volumes:
  mongodbdata:

